DESIGN=prj_hamming_apb
DESDIR=C:\Users\Lesc\Documents\LiberoProjects\prj_hamming_apb - CLC\designer\prj_hamming_apb
TARGET_DIR=C:\Users\Lesc\Documents\LiberoProjects\prj_hamming_apb - CLC\designer\prj_hamming_apb
FAM=SmartFusion2
DIE=PA4M1000_N
PACKAGE=tq144
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
